services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379" # Map localhost:6379 to container's port 6379

  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
      - xpack.security.enrollment.enabled=true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - es01

volumes:
  esdata:
    driver: local  # Ensure that Elasticsearch data is persisted between container restarts

networks:
  esnet:
    driver: bridge